python/pycrdt/doc.py, python/pycrdt/text.py, python/pycrdt/transaction.py, tests/test_ypy.py
=> Allow nested transactions

python/pycrdt/base.py, python/pycrdt/doc.py, python/pycrdt/transaction.py, src/array.rs, src/map.rs, src/text.rs, src/transaction.rs, tests/test_doc.py, tests/test_transaction.py
See https://github.com/y-crdt/y-crdt/pull/353#issuecomment-1815957011.
=> Support read-only transaction in observer callback

docs/index.md
=> Add context and relation to Ypy

pyproject.toml, python/pycrdt/_base.py, tests/test_memory.py
Closes https://github.com/y-crdt/y-crdt/issues/398.
=> Keep subscription references

python/pycrdt/_base.py, python/pycrdt/_doc.py, python/pycrdt/_pycrdt.pyi, tests/test_doc.py
Closes https://github.com/jupyterlab/jupyter-collaboration/issues/253.
=> Fix doc observe

python/pycrdt/_base.py, python/pycrdt/_doc.py, tests/test_doc.py, tests/test_map.py
Filer all code over `pyupgrade --py38-plus'.
=> really drop python<=support

.github/workflows/publish.yml
See https://github.com/jupyter-server/pycrdt/actions/runs/8920105585/job/24497681805.
=> Remove sdist from macOS build

src/doc.rs, tests/test_doc.py
See https://github.com/y-crdt/ypy/pull/104.
=> Ignore empty updates

.github/workflows/publish.yml
=> Publish sdist on PyPI

src/doc.rs, tests/test_doc.py
=> Raise ValueError on Doc.get_update() error

src/array.rs, src/doc.rs, src/map.rs, src/text.rs, tests/test_threads.py
Closes #114
Closes #110
See https://github.com/y-crdt/y-crdt/pull/440.
=> Allow multithreading

.gitignore
When I tried this project I noticed that we were missing `.gitignore`. Just try to add it
=> Chore: add .gitignore

.github/workflows/test.yml, python/pycrdt/__init__.py, python/pycrdt/_array.py, python/pycrdt/_awareness.py, python/pycrdt/_sync.py, python/pycrdt/_text.py, tests/test_transaction.py
This is the `Awareness` from [pycrdt-websocket](https://github.com/jupyter-server/pycrdt-websocket/blob/39ebb2981ef80bbaa867a013675f30091c69535c/pycrdt_websocket/awareness.py).
TODO:
- add a test and remove the [pragma: no cover](https://github.com/jupyter-server/pycrdt/pull/171/files#diff-d0908cdc750b8113ae6b4433e378db136aebe96a30e773aef2cf08313b6669d8R11).
- add docstrings.
=> Add awareness

python/pycrdt/_awareness.py, tests/test_awareness.py
This PR adds the periodic awareness update as in [awareness.js](https://github.com/yjs/y-protocols/blob/255b7e6c96d9c6dd48b5519b3f83ab65afdb4bba/awareness.js#L59).
cc @brichet
=> Add periodic awareness updates

.github/workflows/test.yml, python/pycrdt/_array.py, python/pycrdt/_text.py, tests/test_array.py, tests/test_text.py
=> Fix Array iterator

.github/workflows/publish.yml, .github/workflows/test.yml, docs/usage.md, pyproject.toml, python/pycrdt/_array.py, python/pycrdt/_base.py, python/pycrdt/_doc.py, python/pycrdt/_map.py, tests/test_types.py
=> Support type annotations

tests/test_types.py
See https://github.com/jupyter-server/pycrdt/actions/runs/13250370773/job/36986679118?pr=229.
=> Fix test for typed array

.github/workflows/publish.yml, pyproject.toml
=> Bump trio to <0.30

python/pycrdt/_array.py, python/pycrdt/_doc.py, python/pycrdt/_map.py, python/pycrdt/_pycrdt.pyi, python/pycrdt/_text.py, python/pycrdt/_xml.py, src/doc.rs, tests/test_transaction.py
=> Fix deadlock with getting root type from within transaction

pyproject.toml, python/pycrdt/_base.py, python/pycrdt/_doc.py, tests/conftest.py, tests/test_threads.py, tests/test_transaction.py
This PR also also closes memory streams.
=> Turn warnings into errors in tests

python/pycrdt/_xml.py, src/xml.rs, tests/test_xml.py
=> Support XML insert_embed shared types

python/pycrdt/_base.py, python/pycrdt/_doc.py, python/pycrdt/_pycrdt.pyi, src/doc.rs
=> Support skipping garbage collection

python/pycrdt/_doc.py
=> Expose skip_gc in Doc init

docs/api_reference.md, python/pycrdt/__init__.py, python/pycrdt/_doc.py, python/pycrdt/_pycrdt.pyi, python/pycrdt/_snapshot.py, src/doc.rs, src/lib.rs, src/snapshot.rs, src/text.rs, tests/test_snapshot.py
=> Implement snapshots support

python/pycrdt/_base.py, python/pycrdt/_doc.py, python/pycrdt/_transaction.py, tests/test_transaction.py
=> Support document change async callbacks
